#!/usr/bin/env python3

import sys, os, math, csv
from sys import stdin
from math import factorial, sqrt, exp, pi

fit_tab = [[0, 99, 90, 80, 70, 60, 50, 40, 30, 20, 10, 5, 3, 1],
[1, 0.00, 0.02, 0.06, 0.15, 0.27, 0.45, 0.71, 1.07, 1.64, 2.71, 3.84, 5.41, 6.63],
[2, 0.02, 0.21, 0.45, 0.71, 1.02, 1.39, 1.83, 2.41, 3.22, 4.61, 5.99, 7.82, 9.21],
[3, 0.11, 0.58, 1.01, 1.42, 1.87, 2.37, 2.95, 3.66, 4.64, 6.25, 7.81, 9.84, 11.34],
[4, 0.30, 1.06, 1.65, 2.19, 2.75, 3.36, 4.04, 4.88, 5.99, 7.78, 9.49, 9.84, 11.34],
[5, 0.55, 1.61, 2.34, 3.00, 3.66, 4.35, 5.13, 6.06, 7.29, 9.24, 11.07, 11.67, 13.28],
[6, 0.7, 2.20, 3.07, 3.83, 4.57, 5.35, 6.21, 7.23, 8.56, 10.64, 12.59, 15.03, 16.81],
[7, 1.24, 2.83, 3.82, 4.67, 5.49, 6.35, 7.28, 8.38, 9.80, 12.02, 14.07, 16.62, 18.48],
[8, 1.65, 3.49, 4.59, 5.53, 6.42, 7.34, 8.35, 9.52, 11.03, 13.36, 15.51, 18.17, 20.09],
[9, 2.09, 4.17, 5.38, 6.39, 7.63, 8.34, 9.41, 10.66, 12.24, 14.68, 16.92, 19.68, 21.67],
[10, 2.56, 4.87, 6.18, 7.27, 8.30, 9.34, 10.47, 11.78, 13.44, 15.99, 18.31, 21.16, 23.21]]

def error_handling():
    arg = []
    i = 1
    try:
        while (i < len(sys.argv)):
            arg.append(int(sys.argv[i]))
            i += 1
    except:
        exit(84)
    if sum(arg) != 100 or len(arg) != 9:
        exit (84)
    if len(arg) < 1:
        exit(84)
    return arg

def facto(lim):
    result = 1
    i = 2

    while i <= lim:
        result *= i
        i += 1
    return result

def sum_square(ox, tx):
    res = 0
    for i in range(0, len(ox)):
        res += pow(ox[i] - tx[i], 2) / tx[i]
    return res

def combinaison(n, k):
    num = facto(k)
    denum1 = facto(n)
    denum2 = facto(k - n)
    denum1 *= denum2
    return num / denum1

def param_loi_binomial(valeur_observer):
    res = 0
    for i in range(0, len(valeur_observer)):
        res += (i * valeur_observer[i])
    res /= 100 * 100
    return res

def fit_validity(sum, degr):
    i = 1
    found = False
    while i != 13:
        if fit_tab[degr][i] <= sum <= fit_tab[degr][i + 1]:
            max = fit_tab[0][i]
            min = fit_tab[0][i + 1]
            found = True
            break
        i += 1
    if not found:
        if fit_tab[degr][1] <= sum:
            max = fit_tab[0][13]
            ret = 'P < ' + str(max) + '%'
            return ret
        if fit_tab[degr][13] >= sum:
            max = fit_tab[0][1]
            ret = 'P > ' + str(max) + '%'
            return ret

    ret = str(min) + '% < P < ' + str(max)+'%'
    return ret

def my_loop(tab, newTX):
    inc = 0
    count = 0
    newX = []
    while count < len(tab):
        newX.append(str(inc))
        if count - 1 >= 0 and count + 1 < len(tab) and tab[count] < 10:
            if tab[count - 1] + tab[count] < tab[count + 1] + tab[count]:
                tab[count] += tab[count - 1]
                tab.pop(count - 1)
                newX[count - 1] += '-' + str(inc)
                inc += 1
                newX[count] = str(inc)
                newTX[count] += newTX[count - 1]
                newTX.pop(count - 1)
                while tab[count - 1] < 10:
                    tab[count] += tab[count - 1]
                    tab.pop(count - 1)
                    if count < len(newTX) - 1:
                        newTX[count] += newTX[count - 1]
                        newTX.pop(count - 1)
                    newX[count - 1] += '-' + str(inc)
                    inc += 1
                    if inc < 9:
                        newX.append(str(inc))
                    newX.pop(count)
            else:
                newTX[count] += newTX[count + 1]
                newTX.pop(count+1)
        count += 1
        inc += 1
    return tab, newTX, newX, count, inc

def my_calc_tab(newTab, newX, count, inc):
    if newTab[len(newTab) - 1] < 10:
        newTab[count - 1] += newTab[count - 2]
        newTab.pop(count - 2)
        newX[count - 2] += '-' + str(inc - 1)
        newX.pop(count - 1)
        inc += 1
        while newTab[count - 2] < 10:
            newTab[count] += newTab[count - 1]
            newTab.pop(count - 1)
            newX[count - 1] += '-' + str(inc)
            inc += 1
            newX.pop(count)
    return newTab, newX, count, inc

def my_tab(newTab, newX, newTX, count, inc):
    for i in range(0, len(newX)):
        tmp = newX[i].split('-')
        if len(tmp) != 1:
            newX[i] = tmp[0] + '-' + tmp[len(tmp) - 1]
        if i + 1 == len(newX):
            newX[i] = tmp[0] + '+'
    print(" x\t| ", end="")
    for i in newX:
        print(i + '\t| ', end="")
    print(" total")

    newOX = []
    for i in newTab:
        newOX.append(i)
    print(" Ox\t| ", end="")
    for count in range(0, len(newOX)):
        print(str(newOX[count]) + "\t| ", end="")
    print(" 100")
    print(" Tx\t| ", end="")
    for count in range(0, len(newTX)):
        print("%.1f" % newTX[count] + "\t| ", end="")
    print(" 100")
    return newOX

def my_print_tab(newTab, newTX, newX, count, inc):
    newTab, newX, count, inc = my_calc_tab(newTab, newX, count, inc)
    newOX = my_tab(newTab, newX, newTX, count, inc)
    return newOX, newTX

def my_counter1(tab, binomial):
    newTX = []
    r = 0
    for count in range(0, len(tab) - 1):
        result = 100 * combinaison(count, 100) * pow(binomial, count) * pow((1 - binomial), 100 - count)
        r += result
        newTX.append(result)
    newTX.append(100 - r)
    return newTX

def my_squarenfit(newOX, newTX):
    sum = sum_square(newOX, newTX)
    print("Chi-squared:\t\t\t%.3f"%sum)
    degr = len(newOX) - 2
    print("Degrees of freedom:\t\t{}".format(degr))
    print("Fit validity:\t\t\t" + fit_validity(sum, degr))
    exit(0)

def main():
    tab = error_handling()
    binomial = param_loi_binomial(tab)
    TX = my_counter1(tab, binomial)
    newTab, newTx, newX, count, inc = my_loop(tab, TX)
    newOX, newTX = my_print_tab(newTab, newTx, newX, count, inc)
    print("Distribution:\t\t\tB(100, %.4f)" % binomial)
    my_squarenfit(newOX, newTX)
    return 0

main()
